In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
#get a specific element [r,c]
a[1,5]


13

In [4]:
#get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
#coloumn
a[:,2]

array([ 3, 10])

In [7]:
a[0,1:-1:2]

array([2, 4, 6])

In [11]:
a[1,5]=20
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [9]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [16]:
#3d

In [13]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])b
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
b[0,1,1]

4

In [18]:
b[:,1,:]=[[9,9,],[8,8]]

In [19]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [20]:
# initializating different types of array

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [23]:
#any other number
np.full((2,2),33)

array([[33, 33],
       [33, 33]])

In [24]:
#any other full like
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
np.random.randint(-4,8,size=(3,3))

array([[ 4,  5,  1],
       [ 2,  7,  1],
       [-4,  3, -4]])

In [26]:
np.random.rand(4,2)

array([[0.01095166, 0.06530882],
       [0.90987177, 0.16120198],
       [0.01385722, 0.6922967 ],
       [0.46963546, 0.75236753]])

In [27]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#reapat an arrya
arr = np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
a = np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3]
[1 2 3]


In [19]:
import numpy as np
output = np.ones((5,5))
print(output)
z=np.zeros((3,3))
#print(z)
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:

#Mathematics


In [26]:
a =np.arange(1,5)
a

array([1, 2, 3, 4])

In [27]:
a+2

array([3, 4, 5, 6])

In [28]:
a-2

array([-1,  0,  1,  2])

In [29]:
a*2

array([2, 4, 6, 8])

In [30]:
a**2

array([ 1,  4,  9, 16])

In [31]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [41]:
b=np.array([1,1,0,1])
b

array([1, 1, 0, 1])

In [33]:
a+b

array([2, 3, 4, 5])

In [34]:
# take sin cos tan
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [35]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [36]:
np.tan(a)


array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [37]:

#linear algebra


In [52]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
b= np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [53]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [54]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
#to find thr drtrtminrnt
np.linalg.det(c)

1.0

In [56]:
a.dot(b)

array([[6., 6.],
       [6., 6.]])

In [57]:
a.dot(c)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np.dot(a,np.ones(3))

array([3., 3.])

In [60]:
a@np.ones(3)

array([3., 3.])

In [65]:
#from numpy.linalg import inv,qr
x = np.random.randn(5,5)
mat = x.T.dot(x)
inv(mat)

array([[ 0.67217302,  0.37509033,  1.21609324, -0.7120944 ,  0.74864185],
       [ 0.37509033,  0.87891111, -0.26124441, -0.91415623,  0.57518278],
       [ 1.21609324, -0.26124441,  4.23584659, -0.50487514,  1.1989257 ],
       [-0.7120944 , -0.91415623, -0.50487514,  2.41649533, -1.44664102],
       [ 0.74864185,  0.57518278,  1.1989257 , -1.44664102,  1.27185599]])

In [66]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -2.47642914e-16, -1.72058051e-15,
         8.27683151e-16,  2.58742758e-16],
       [-5.17062740e-16,  1.00000000e+00,  9.84751609e-16,
        -2.45485797e-16,  2.15685282e-16],
       [-3.15830467e-16,  2.23977180e-16,  1.00000000e+00,
        -4.55335440e-16,  6.16976192e-16],
       [-4.46099733e-17, -3.50859893e-16, -1.04227208e-15,
         1.00000000e+00, -6.20253694e-16],
       [ 1.86173718e-16, -4.17269308e-18, -5.51466672e-16,
         4.84094607e-16,  1.00000000e+00]])

In [67]:
q,r =qr(mat)

In [68]:
r

array([[-14.4462543 ,   6.75948664,   3.93358058,   0.77855788,
          2.75137663],
       [  0.        ,  -2.80594226,  -1.29194661,   1.25857227,
          4.36450916],
       [  0.        ,   0.        ,  -1.07319066,   2.77452561,
          4.65428768],
       [  0.        ,   0.        ,   0.        ,  -0.84029357,
         -0.97398506],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.40692419]])

In [69]:
np.trace(c)

3.0

In [70]:
np.diag(c)

array([1., 1., 1.])

In [72]:
np.linalg.det(c)

1.0

In [74]:
np.linalg.eig(c)

(array([1., 1., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [76]:
np.linalg.inv(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
np.linalg.pinv(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.linalg.solve(c,b)

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

# Statistics

In [86]:
stat =np.array([[1,2,3],[4,5,6]])
stat

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np.min(stat)

1

In [88]:
np.max(stat)

6

In [89]:
np.min(stat,axis=1)

array([1, 4])

In [90]:
np.max(stat,axis=0)

array([4, 5, 6])

In [91]:
np.sum(stat)

21

In [92]:
np.sum(stat,axis =0)

array([5, 7, 9])

Reorganizing Arrays

In [99]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [100]:
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [102]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [103]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [104]:
np.vstack([v1,v2,v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [105]:
# Horizontal stack

In [107]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [108]:
h2

array([[0., 0.],
       [0., 0.]])

In [110]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

MIscellaneous

load data from file

In [112]:
np.genfromtxt('test.txt',delimiter=',')

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [119]:
filetest = np.genfromtxt('test.txt',delimiter=',')
filetest=filetest.astype('int32')
print(filetest)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# boolean masking and advnaced indexing

In [121]:
filetest >50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [120]:
filetest[filetest >50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [123]:
#we can index with  a list in numpy
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]


array([2, 3, 9])

In [133]:
(~np.any(filetest >50,axis=0))

array([ True,  True,  True,  True, False, False,  True, False, False,
        True,  True,  True,  True,  True,  True,  True, False, False])

In [129]:
np.all(filetest >50,axis=1)

array([False, False, False])

In [131]:
(~((filetest>50) & (filetest <100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [152]:
a=np.arange(30).reshape(6,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [153]:
a[2:4,0:2]

array([[10, 11],
       [15, 16]])

In [154]:
a[2:4,1:3]

array([[11, 12],
       [16, 17]])

In [155]:
a[[0,1,2,3],[1,2,3,4]]

array([ 1,  7, 13, 19])

In [157]:
a[[0,4,5],3:]

array([[ 3,  4],
       [23, 24],
       [28, 29]])

In [158]:
a.mean()

14.5

In [161]:
a.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325,
       351, 378, 406, 435])

In [162]:
a.cumsum(axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13],
       [15, 18, 21, 24, 27],
       [30, 34, 38, 42, 46],
       [50, 55, 60, 65, 70],
       [75, 81, 87, 93, 99]])

In [163]:
a.cumsum(axis=1)

array([[  0,   1,   3,   6,  10],
       [  5,  11,  18,  26,  35],
       [ 10,  21,  33,  46,  60],
       [ 15,  31,  48,  66,  85],
       [ 20,  41,  63,  86, 110],
       [ 25,  51,  78, 106, 135]])

In [164]:
a.std()

8.65544144839919

In [165]:
a.var()

74.91666666666667

In [166]:
a.argmin()

0

In [167]:
a.argmax()

29

In [168]:
a.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [169]:
a.cumprod(axis=0)

array([[      0,       1,       2,       3,       4],
       [      0,       6,      14,      24,      36],
       [      0,      66,     168,     312,     504],
       [      0,    1056,    2856,    5616,    9576],
       [      0,   22176,   62832,  129168,  229824],
       [      0,  576576, 1696464, 3616704, 6664896]])

In [170]:
a.cumprod(axis=1)

array([[       0,        0,        0,        0,        0],
       [       5,       30,      210,     1680,    15120],
       [      10,      110,     1320,    17160,   240240],
       [      15,      240,     4080,    73440,  1395360],
       [      20,      420,     9240,   212520,  5100480],
       [      25,      650,    17550,   491400, 14250600]])