In [1]:
import numpy as np
import time
import sys
import array
l=  range(1000)
print(sys.getsizeof(5)*len(l))

array =np.arange(1000)
print(array.size*array.itemsize)

28000
4000


In [ ]:
#basic operation

In [5]:
a = np.array([5,6,7])
a[0]


5

In [6]:
a[1]

6

In [11]:
b = np.array([[1,2],[3,4]])
b.ndim


2

In [10]:
a.ndim

1

In [12]:
b.itemsize

4

In [14]:
a.dtype

dtype('int32')

In [21]:
c=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
c.dtype

dtype('float64')

In [22]:
c.itemsize

8

In [23]:
c.size

6

In [24]:
c.shape

(3, 2)

In [26]:
complex=np.array([[1,2],[3,4],[5,6]],dtype=complex)
complex

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
l = range(5)
l

range(0, 5)

In [30]:
l[0]

0

In [31]:
l[2]

2

In [32]:
np.arange(1,5)

array([1, 2, 3, 4])

In [33]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [34]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [36]:
np.linspace(1,5,30)

array([1.        , 1.13793103, 1.27586207, 1.4137931 , 1.55172414,
       1.68965517, 1.82758621, 1.96551724, 2.10344828, 2.24137931,
       2.37931034, 2.51724138, 2.65517241, 2.79310345, 2.93103448,
       3.06896552, 3.20689655, 3.34482759, 3.48275862, 3.62068966,
       3.75862069, 3.89655172, 4.03448276, 4.17241379, 4.31034483,
       4.44827586, 4.5862069 , 4.72413793, 4.86206897, 5.        ])

In [37]:
c=np.array([[1,2],[3,4],[5,6]])

In [40]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
c.shape

(3, 2)

In [42]:
c.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [44]:
c.ravel()

array([1, 2, 3, 4, 5, 6])

In [45]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
c.min()

1

In [48]:
c.max()

6

In [49]:
c.sum()

21

In [52]:
c.sum(axis =0)

array([ 9, 12])

In [53]:
c.sum(axis=1)

array([ 3,  7, 11])

In [54]:
np.sqrt(c)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [55]:
np.std(c)

1.707825127659933

In [57]:
d=np.array([[1,2],[3,4]])
c=np.array([[5,6],[7,8]])
d

array([[1, 2],
       [3, 4]])

In [58]:
c

array([[5, 6],
       [7, 8]])

In [59]:
c+d

array([[ 6,  8],
       [10, 12]])

In [60]:
c*d

array([[ 5, 12],
       [21, 32]])

In [64]:
d/c

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [63]:
d.dot(c)

array([[19, 22],
       [43, 50]])

In [65]:


# indexing \iterating\stacking\indexing with boolean arrays




In [66]:
n = [3,5,6]
n[0:2]

[3, 5]

In [67]:
n[-1]

6

In [68]:
a = np.array([5,6,7])
a[0:2]

array([5, 6])

In [69]:
a[-1]

7

In [75]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
d[1,2]

6

In [79]:
d[0:2,1]

array([2, 5])

In [80]:
d[-1]

array([7, 8, 9])

In [82]:
d[-1,0:2]

array([7, 8])

In [84]:
d[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [85]:
#iterating

In [86]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [89]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [90]:
#stacking

In [91]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [92]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [93]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [94]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [95]:
c=np.arange(30).reshape(2,15)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [96]:
np.hsplit(c,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [98]:
result = np.hsplit(c,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [99]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [100]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [103]:
result = np.vsplit(c,2)

In [104]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [105]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [106]:
#indexing with boolean

In [107]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [109]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [110]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [111]:


# Read write text files



In [118]:
x =np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [119]:
np.savetxt("test.txt",x)

In [120]:
y = np.loadtxt("test.txt")
print(y)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]


In [ ]:


#iterate using nditer



In [128]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [130]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [131]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [132]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [133]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [134]:
for x in np.nditer(a,order ='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [135]:
for x in np.nditer(a,op_flags =['readwrite']):
    x[...]=x*x

In [136]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [137]:
b = np.arange(3,15,4).reshape(3,1)

In [138]:
b

array([[ 3],
       [ 7],
       [11]])

In [139]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [5]:
from numpy import random
import numpy as np
x = random.randint(100,size=(5))

In [6]:
x

array([47,  5, 54, 37, 90])

In [8]:
from numpy import random
x = random.randint(100,size=(5,3))
x

array([[82, 90, 35],
       [27,  6, 98],
       [93, 47, 47],
       [90, 93, 24],
       [87, 14, 95]])

In [10]:
x= random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(3,5))
print (x)

[[7 7 7 7 5]
 [7 5 7 5 7]
 [7 5 7 5 5]]


In [15]:
from numpy import random
import numpy as np
arr = np.array([1,2,3,4,5])
random.shuffle(arr)

In [16]:
print(arr)

[1 3 5 4 2]


In [17]:
arr = np.array([1,2,3,4,5])
print(random.permutation(arr))

[5 2 4 3 1]


In [18]:
x=random.normal(loc=1,scale=2,size=(2,3))
x

array([[ 5.21677962, -1.02618641,  3.67665549],
       [ 3.20380879,  2.05296854,  2.89089016]])